# Generated by Django 6.0.2 on 2026-03-11 02:25

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the library', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Library creation timestamp')),
            ],
            options={
                'verbose_name': 'Library',
                'verbose_name_plural': 'Libraries',
                'db_table': 'libraries',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the user', primary_key=True, serialize=False)),
                ('email', models.EmailField(help_text='User email address (from Google OAuth)', max_length=254, unique=True)),
                ('username', models.CharField(help_text='Username for display purposes', max_length=150, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Account creation timestamp')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the song', primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Song title', max_length=200)),
                ('genre', models.CharField(choices=[('Rock', 'Rock'), ('Pop', 'Pop'), ('Jazz', 'Jazz'), ('HipHop', 'Hip Hop'), ('Country', 'Country')], default='Pop', help_text='Primary musical genre', max_length=20)),
                ('mood', models.CharField(choices=[('Happy', 'Happy'), ('Sad', 'Sad'), ('Energetic', 'Energetic'), ('Calm', 'Calm')], default='Happy', help_text='Emotional mood/tone', max_length=20)),
                ('occasion', models.CharField(choices=[('Birthday', 'Birthday'), ('Wedding', 'Wedding'), ('Funeral', 'Funeral'), ('Party', 'Party'), ('Relaxation', 'Relaxation'), ('Workout', 'Workout'), ('Study', 'Study'), ('Other', 'Other')], default='Other', help_text='Context or occasion for the song', max_length=20)),
                ('singer_voice', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Neutral', 'Neutral'), ('Duet', 'Duet')], default='Male', help_text='Preferred singer voice type', max_length=20)),
                ('prompt', models.TextField(blank=True, default='', help_text='Optional extended prompt (max 1000 characters)', max_length=1000, validators=[django.core.validators.MaxLengthValidator(1000)])),
                ('status', models.CharField(choices=[('Queued', 'Queued'), ('Generating', 'Generating'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Queued', help_text='Current generation status', max_length=20)),
                ('duration', models.IntegerField(blank=True, help_text='Song duration in seconds (max 900/15 minutes)', null=True, validators=[django.core.validators.MaxValueValidator(900)])),
                ('audio_format', models.CharField(choices=[('MP3', 'MP3'), ('M4A', 'M4A (AAC)'), ('WAV', 'WAV')], default='MP3', help_text='Output audio format', max_length=10)),
                ('audio_file_url', models.URLField(blank=True, default='', help_text='URL to the generated audio file')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Song creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
                ('library', models.ForeignKey(help_text='Library that contains this song', on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='domain.library')),
            ],
            options={
                'verbose_name': 'Song',
                'verbose_name_plural': 'Songs',
                'db_table': 'songs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShareLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the share link', primary_key=True, serialize=False)),
                ('token', models.CharField(db_index=True, help_text='Unique access token for sharing', max_length=32, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Share link creation timestamp')),
                ('song', models.OneToOneField(help_text='Song associated with this share link', on_delete=django.db.models.deletion.CASCADE, related_name='share_link', to='domain.song')),
            ],
            options={
                'verbose_name': 'Share Link',
                'verbose_name_plural': 'Share Links',
                'db_table': 'share_links',
            },
        ),
        migrations.AddField(
            model_name='library',
            name='user',
            field=models.OneToOneField(help_text='Owner of this library', on_delete=django.db.models.deletion.CASCADE, related_name='library', to='domain.user'),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['library', '-created_at'], name='songs_library_5169c7_idx'),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['status'], name='songs_status_6e3180_idx'),
        ),
    ]
