# Generated by Django 6.0.2 on 2026-03-22 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='occasion',
            field=models.CharField(choices=[('Birthday', 'Birthday'), ('Wedding', 'Wedding'), ('Funeral', 'Funeral'), ('Party', 'Party'), ('Relaxation', 'Relaxation'), ('Study', 'Study'), ('Other', 'Other')], default='Other', help_text='Context or occasion for the song', max_length=20),
        ),
        migrations.AlterField(
            model_name='song',
            name='singer_voice',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', help_text='Preferred singer voice type', max_length=20),
        ),
    ]
