# Generated by Django 6.0.2 on 2026-04-02 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0002_alter_song_occasion_alter_song_singer_voice'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='provider_task_id',
            field=models.CharField(blank=True, help_text='Task ID from the generation provider (e.g., Suno)', max_length=255, null=True),
        ),
    ]
