# Generated by Django 4.2.30 on 2026-04-18 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0003_song_provider_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='occasion',
            field=models.CharField(choices=[('Birthday', 'Birthday'), ('Wedding', 'Wedding'), ('Funeral', 'Funeral'), ('Party', 'Party'), ('Relaxation', 'Relaxation'), ('Study', 'Study'), ('Workout', 'Workout'), ('Other', 'Other')], default='Other', help_text='Context or occasion for the song', max_length=20),
        ),
    ]
