version: "3.8"

services:
  backend:
    build:
      context: ./Cithara
      dockerfile: Dockerfile
    container_name: cithara-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./Cithara:/app
    networks:
      - cithara-network

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: cithara-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    networks:
      - cithara-network
    depends_on:
      - backend

networks:
  cithara-network:
    driver: bridge
